spring:
  redis:
    host: 120.131.6.144
    password: chaoxing
    port: 10002
  datasource:
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=UTC&characterEncoding=UTF-8
    #    url: jdbc:postgresql://101.132.110.182:5432/exam
    username: root
    password: hzc778209
